services:
  subway.mvp.apis.freshmenu:
    image: ${DOCKER_REGISTRY-}subwaymvpapisfreshmenu
    container_name: subway.mvp.apis.freshmenu
    build:
      context: .
      dockerfile: src/Subway.Mvp.Apis.FreshMenu/Dockerfile
    ports:
      - 5262:5262
      - 7194:7194

  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    expose:
      - "5150"
    ports:
      - 5150:8080
      - 38888:38888
    restart: always
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
    volumes:
      - ./.containers/ravendb/data:/var/lib/ravendb/data 

